### ISSUE TITLE
[BUG]Error when starting the server

### ISSUE THREAD

**Issue by dixiatielu** [Slimefun-Addon-Community/LiteXpansion#10]
## Description (REQUIRED)

An error occured when starting the server.

## Steps to reproduce the Issue (REQUIRED)

Start the server with the versions in the last of the issue.

## Expected behavior (REQUIRED)

Enable the plugin properly.

## Server Log

**Here is the error log**
```
[21:33:30 WARN]: [LiteXpansion] MassFabricator - 'MASS_FABRICATOR_MACHINE' (LiteXpansion vDEV - 114 (git 061c0798)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[21:33:30 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[21:33:30 WARN]: [LiteXpansion] Generator - 'GENERATOR' (LiteXpansion vDEV - 114 (git 061c0798)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[21:33:30 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[21:33:30 ERROR]: Error occurred while enabling LiteXpansion vDEV - 114 (git 061c0798) (Is it up to date?)
java.lang.NoSuchFieldError: NETHER_GOLD_ORE
        at dev.j3fftw.litexpansion.machine.Macerator.registerDefaultRecipes(Macerator.java:71) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.register(AContainer.java:236) ~[?:?]
        at dev.j3fftw.litexpansion.ItemSetup.registerMachines(ItemSetup.java:81) ~[?:?]
        at dev.j3fftw.litexpansion.ItemSetup.init(ItemSetup.java:54) ~[?:?]
        at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:59) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-390]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

## Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/29675002/103458545-352a1f80-4d44-11eb-9b0d-6e80d2c6ad6f.png)

**Comment by Riley31415** [comment]
Get a 1.16 server

**Comment by dixiatielu** [comment]
> Get a 1.16 server



> Get a 1.16 server

However there is still a supported version of MC version 1.14.x and 1.15.x in the download page
![image](https://user-images.githubusercontent.com/29675002/104092132-f274c400-52bc-11eb-9ecf-10d0ada63e35.png)

Could you please update the build page so that we can downgrade the plugin version?

**Comment by J3fftw1** [comment]
It does support 1.14 and up i made a small mistake that should be fixed in thr latedt version

**Comment by dixiatielu** [comment]
> It does support 1.14 and up i made a small mistake that should be fixed in thr latedt version

Okay, I'm waiting for your latest version😄

**Comment by J3fftw1** [comment]
https://thebusybiscuit.github.io/builds/J3fftw1/LiteXpansion/master/#116

**Comment by dixiatielu** [comment]
Thanks, i'll try it

**Comment by dixiatielu** [comment]
> https://thebusybiscuit.github.io/builds/J3fftw1/LiteXpansion/master/#116

The issue still exists when i use build 120
```
[23:28:06 INFO]: [LiteXpansion] Enabling LiteXpansion vDEV - 120 (git 58144723)
[23:28:07 WARN]: [LiteXpansion] Generator - 'GENERATOR' (LiteXpansion vDEV - 120 (git 58144723)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[23:28:07 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[23:28:07 WARN]: [LiteXpansion] Macerator - 'MACERATOR' (LiteXpansion vDEV - 120 (git 58144723)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[23:28:07 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[23:28:07 WARN]: [LiteXpansion] RubberSynthesizer - 'RUBBER_SYNTHESIZER' (LiteXpansion vDEV - 120 (git 58144723)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[23:28:07 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[23:28:07 ERROR]: Error occurred while enabling LiteXpansion vDEV - 120 (git 58144723) (Is it up to date?)
java.lang.NoSuchFieldError: NETHERITE_INGOT
        at dev.j3fftw.litexpansion.ItemSetup.registerMiscItems(ItemSetup.java:221) ~[?:?]
        at dev.j3fftw.litexpansion.ItemSetup.init(ItemSetup.java:56) ~[?:?]
        at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-390]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[23:28:07 INFO]: [LiteXpansion] Disabling LiteXpansion vDEV - 120 (git 58144723)

```
