### ISSUE TITLE
[BUG] Exception while looking for updates

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun-Addon-Community/LiteXpansion#21]
## Description (REQUIRED)

When LX checks for updates, it **always** results in a `FileNotFoundException`

## Steps to reproduce the Issue (REQUIRED)

1. Set up a Server with the latest LX build installed
2. Wait for it to check for updates

## Expected behavior (REQUIRED)

The update-check should not always fail.
Perhaps you are using the wrong url?

## Server Log

(The error is small enough, so no need for pastebin here)
```
[13:51:58 WARN]: [LiteXpansion] Could not connect to the updating site, is it down?
java.io.FileNotFoundException: https://thebusybiscuit.github.io/builds/Slimefun-Addon-Community/LiteXpansion/master/builds.json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1923) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at me.mrCookieSlime.Slimefun.cscorelib2.updater.UpdaterTask.getLatestVersion(UpdaterTask.java:66) ~[?:?]
        at me.mrCookieSlime.Slimefun.cscorelib2.updater.UpdaterTask.run(UpdaterTask.java:46) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft version: 1.16.4
 - CS-CoreLib version: *None* :PogChamp:
 - Slimefun version: DEV 791
 - LiteXpansion version: DEV 124

**Comment by TheBusyBiscuit** [comment]
Closed via https://github.com/Slimefun-Addon-Community/LiteXpansion/commit/f5cdd4a812879e8bd0405b6c6e3d7e92f532a642
