### ISSUE TITLE
[BUG]Unknown STICKY_RESIN & No UU-Matter registering method & deprecated interface

### ISSUE THREAD

**Issue by dixiatielu** [Slimefun-Addon-Community/LiteXpansion#23]
## Description (REQUIRED)

When I start my server, several errors was thrown, and the plugin cannot be enabled.

## Steps to reproduce the Issue (REQUIRED)

nothing but starting the server, my current plugin version is v124.

## Expected behavior (REQUIRED)

It is supposed to be enabled properly

## Server Log

Here are the logs
```
[14:09:13 INFO]: [LiteXpansion] Enabling LiteXpansion vDEV - 124 (git 0e449831)
[14:09:13 WARN]: [LiteXpansion] Generator - 'GENERATOR' (LiteXpansion vDEV - 124 (git 0e449831)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[14:09:13 WARN]: [LiteXpansion] You can report this warning here: https://github.com/Slimefun-Addon-Community/LiteXpansion/issues
[14:09:13 WARN]: [LiteXpansion] Macerator - 'MACERATOR' (LiteXpansion vDEV - 124 (git 0e449831)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[14:09:13 WARN]: [LiteXpansion] You can report this warning here: https://github.com/Slimefun-Addon-Community/LiteXpansion/issues
[14:09:13 WARN]: [LiteXpansion] RubberSynthesizer - 'RUBBER_SYNTHESIZER' (LiteXpansion vDEV - 124 (git 0e449831)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[14:09:13 WARN]: [LiteXpansion] You can report this warning here: https://github.com/Slimefun-Addon-Community/LiteXpansion/issues
[14:09:13 WARN]: [LiteXpansion] Unable to create recipe, unknown output item: STICKY_RESIN
[14:09:13 INFO]: [LiteXpansion] Loaded 34 UU-Matter recipes
[14:09:13 ERROR]: Error occurred while enabling LiteXpansion vDEV - 124 (git 0e449831) (Is it up to date?)
java.lang.NoSuchMethodError: dev.j3fftw.litexpansion.uumatter.UuMatterCategory.register(Lio/github/thebusybiscuit/slimefun4/api/SlimefunAddon;)V
        at dev.j3fftw.litexpansion.uumatter.UUMatter.register(UUMatter.java:70) ~[?:?]
        at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[14:09:13 INFO]: [LiteXpansion] Disabling LiteXpansion vDEV - 124 (git 0e449831)
```

## Environment (REQUIRED)

Here is the screenshot:
![image](https://user-images.githubusercontent.com/29675002/106103475-f8ebb280-617b-11eb-94e2-04c9db1cce0d.png)

**Comment by J3fftw1** [comment]
You are using an unsupported version of slimefun!

**Comment by dixiatielu** [comment]
> You are using an unsupported version of slimefun!

Thank you, but what should I do and what caused the problem? Doesn't this plugin supports the official build #511 and up?

**Comment by J3fftw1** [comment]
It supports the latest version not sure which 1 it is. I cba to update the build page
