### ISSUE TITLE
[BUG]same id in LiteXpansion and BeyondHorizons !

### ISSUE THREAD

**Issue by ljs666** [Slimefun-Addon-Community/LiteXpansion#85]
## Description (REQUIRED)
there is an item called "COAL_DUST"that has cause error in server
this item id had both used in BeyondHorizons and LiteXpansion

## Steps to reproduce the Issue (REQUIRED)
<maybe some of you should change this item id>

## Expected behavior (REQUIRED)
<this will be helpful thx>

## Server Log
[12:59:36] [Server thread/INFO]: [LiteXpansion] Enabling LiteXpansion vBuild 26 (git 6efc2c9)
[12:59:36] [Server thread/ERROR]: [LiteXpansion] Plugin LiteXpansion vBuild 26 (git 6efc2c9) has failed to register events for class dev.j3fftw.litexpansion.items.CargoConfigurator because com/xzavier0722/mc/plugin/slimefun4/storage/controller/SlimefunBlockData does not exist.
[12:59:36] [Server thread/ERROR]: [LiteXpansion] Item "COAL_DUST" from LiteXpansion vBuild 26 (git 6efc2c9) has caused an Error!
[12:59:36] [Server thread/ERROR]: [LiteXpansion] You can report it here: https://github.com/SlimefunGuguProject/LiteXpansion/issues
[12:59:36] [Server thread/ERROR]: [LiteXpansion] Registering DyeItem - 'COAL_DUST' (LiteXpansion vBuild 26 (git 6efc2c9)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: DyeItem - 'COAL_DUST' (LiteXpansion vBuild 26 (git 6efc2c9)) and SlimefunItem - 'COAL_DUST' (BeyondHorizons v1.0.2)
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:598) ~[Slimefun-v2023.02-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:427) ~[Slimefun-v2023.02-release.jar:?]
	at dev.j3fftw.litexpansion.ItemSetup.registerCarbonStuff(ItemSetup.java:258) ~[LiteXpansion-Build 26 (git 6efc2c9).jar:?]
	at dev.j3fftw.litexpansion.ItemSetup.init(ItemSetup.java:63) ~[LiteXpansion-Build 26 (git 6efc2c9).jar:?]
	at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:57) ~[LiteXpansion-Build 26 (git 6efc2c9).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:59:36] [Server thread/INFO]: [LiteXpansion] Loaded 35 UU-Matter recipes

## Environment (REQUIRED)

 - Server Software (Paper):
 - Minecraft version:1.19.1
 - CS-CoreLib version:......
 - Slimefun version:v2023.3 release
 - LiteXpansion version:the newest

**Comment by Sefiraat** [comment]
What is BeyondHorizons?

**Comment by J3fftw1** [comment]
an old addon by tweep which is in beta and shouldnt be used on live severs as its own message says
https://github.com/TweepCoding/Beyond_Horizons

**Comment by Sefiraat** [comment]
Oh I'd never heard of it, before my time with Slimefun it seems :D
If it recommends not using it in a live environment, AND last updated Apr 2020 meaning it will not work on the most recent Slimefun version(s) regardless, then I don't see any purpose making a change for this in the largest SF Addon currently. A SF recipe rewrite would fix this or Tweep can get in touch if they plan to work on the project again?

**Comment by ljs666** [comment]
you're right sir thank you !
