### ISSUE TITLE
[BUG] LiteXpansion does not support 1.20.4 

### ISSUE THREAD

**Issue by ProfElements** [Slimefun-Addon-Community/LiteXpansion#90]
## Description (REQUIRED)

LiteXpansion does not enabled on 1.20.4 due to it using no longer available java classes.

## Steps to reproduce the Issue (REQUIRED)

Download blob.build LiteXpansion. put in minecraft server. see logs 

## Expected behavior (REQUIRED)

It to work on 1.20.4

## Server Log

```

Dec 14 13:45:20 pop-os java[2160069]: [13:45:20 INFO]: [LiteXpansion] Disabling LiteXpansion vDEV - 192 (git 661862ed)
Dec 14 13:45:20 pop-os java[2160069]:         at java.lang.Thread.run(Thread.java:840) ~[?:?]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:552) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:43) ~[LiteXpansion.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at dev.j3fftw.litexpansion.LiteXpansion.registerEnchantments(LiteXpansion.java:68) ~[LiteXpansion.jar:?]
Dec 14 13:45:20 pop-os java[2160069]: java.lang.NoSuchMethodError: 'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
Dec 14 13:45:20 pop-os java[2160069]: [13:45:20 ERROR]: Error occurred while enabling LiteXpansion vDEV - 192 (git 661862ed) (Is it up to date?)
```
## Environment (REQUIRED)

![image](https://github.com/Slimefun-Addon-Community/LiteXpansion/assets/43350117/9fef4dd5-773a-468a-88aa-3fa4a8b1a37d)

**Comment by ianchb** [comment]
Seems it's because of this change:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/977a1fb45ff48f499c5936f40dc6d9f877bab19c#src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fenchantments%2FEnchantment.java

**Comment by Kunnik** [comment]
Hello, can I have some status update on this one please? Looks like a major bug (the addon is not working in latest version of mc) but does not seems to be comming to a solution. 

At least if you are working on it or the addon will no longer be maintained.

**Comment by J3fftw1** [comment]
There is no update on this. I’m also not working on it anymore it’s not abandoned but also not worked on currently

**Comment by mVtZWFu** [comment]
plz update

**Comment by CassieRoseZA** [comment]
Please can you update
